#!/bin/bash

. ./settings.sh
. ./lib.sh

set -e

before=$(free_space)
truncate -s 16M $MOUNT_POINT/testfile
./ccp $MOUNT_POINT/testfile $MOUNT_POINT/testfile-copy
after=$(free_space)

no_blocks_allocated $before $after

diff $MOUNT_POINT/testfile $MOUNT_POINT/testfile-copy

check_for_oops
