#!/bin/bash

. ./settings.sh
. ./lib.sh

set -e

head -c $[ 16 * 1024 * 1024 ] /dev/zero > $MOUNT_POINT/testfile

before=$(free_space)
./ccp $MOUNT_POINT/testfile $MOUNT_POINT/testfile-copy1
./ccp $MOUNT_POINT/testfile $MOUNT_POINT/testfile-copy2
./ccp $MOUNT_POINT/testfile $MOUNT_POINT/testfile-copy3
after=$(free_space)

no_blocks_allocated $before $after

diff $MOUNT_POINT/testfile $MOUNT_POINT/testfile-copy1
diff $MOUNT_POINT/testfile $MOUNT_POINT/testfile-copy2
diff $MOUNT_POINT/testfile $MOUNT_POINT/testfile-copy3

check_for_oops
