#!/bin/bash

. ./settings.sh
. ./lib.sh

set -e

$ddzero bs=1M count=1 of=$MOUNT_POINT/testfile
before=$(free_space)
./ccp $MOUNT_POINT/testfile $MOUNT_POINT/testfile-copy
after=$(free_space)
no_blocks_allocated $before $after

# append some data, so the copy will have different size

before=$(free_space)
seq 1 2048 >> $MOUNT_POINT/testfile-copy
after=$(free_space)

some_blocks_allocated $before $after

$ddzero bs=1M count=1 | diff - $MOUNT_POINT/testfile
(cat $MOUNT_POINT/testfile; seq 1 2048) | diff - $MOUNT_POINT/testfile-copy

check_for_oops
