#!/bin/bash

. ./settings.sh
. ./lib.sh

set -e

head -c $[ 1024 * 1024 ] /dev/zero > $MOUNT_POINT/testfile

before=$(free_space)
./ccp $MOUNT_POINT/testfile $MOUNT_POINT/testfile-copy
./mmap-tool $MOUNT_POINT/testfile-copy RDWR SHARED read 40960 4096 | diff - <(head -c 4096 /dev/zero)
after=$(free_space)

no_blocks_allocated $before $after

diff $MOUNT_POINT/testfile $MOUNT_POINT/testfile-copy

seq 1041 -1 2 | ./mmap-tool $MOUNT_POINT/testfile-copy RDWR SHARED write 40960 4096
($ddzero bs=4096 count=10; seq 1041 -1 2; $ddzero bs=4096 count=245) | diff - $MOUNT_POINT/testfile-copy

after=$(free_space)
some_blocks_allocated $before $after

check_for_oops
