#!/bin/bash

. ./settings.sh
. ./lib.sh

set -e

before_all=$(free_space)
head -c $[ 16 * 1024 * 1024 ] /dev/zero > $MOUNT_POINT/testfile

before=$(free_space)
./ccp $MOUNT_POINT/testfile $MOUNT_POINT/testfile-copy
after=$(free_space)

no_blocks_allocated $before $after

unlink $MOUNT_POINT/testfile
after=$(free_space)

no_blocks_allocated $before $after

unlink $MOUNT_POINT/testfile-copy
after=$(free_space)

no_blocks_allocated $before_all $after

check_for_oops
