#!/bin/bash

. ./settings.sh
. ./lib.sh

set -e

$ddzero bs=1M count=1 of=$MOUNT_POINT/testfile
before=$(free_space)
./ccp $MOUNT_POINT/testfile $MOUNT_POINT/testfile-copy
after=$(free_space)
no_blocks_allocated $before $after

before=$(free_space)
seq 2 1041 | dd status=none of=$MOUNT_POINT/testfile-copy seek=10 bs=4096 count=1 conv=notrunc
after=$(free_space)

some_blocks_allocated $before $after

$ddzero bs=1M count=1 | diff - $MOUNT_POINT/testfile
($ddzero bs=4096 count=10; seq 2 1041; $ddzero bs=4096 count=245) | diff - $MOUNT_POINT/testfile-copy

check_for_oops
